name: Ruby Gem

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: push gem
        uses: trocco-io/push-gem-to-gpr-action@v1
        with:
          language: java
          gem-path: "./build/gems/*.gem"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
